server:
  port: 8088

eureka:
  client:
    service-url.defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yywzgh/spring-cloud-config
          username: root@gmail.com
          password: root
          search-paths: myconfig

security:  
  basic:    
    enabled: true               
    user:
      name: admin
      password: a123456